import Foundation

// GENERATED by scripts/gen_test_runner.py — re-run it after adding a test.
//
// XCTest ships only inside Xcode. When Xcode left this machine all 78 tests
// became unrunnable and audio concurrency code was changed for an evening with
// no safety net. The suite never needed the framework: it is pure logic using
// seven assertions, no setUp, no expectations, no async. So it runs as a plain
// executable instead — `swift run vf-tests` — with or without Xcode present.

func suite(_ name: String, _ body: () -> Void) {
    print("  \(name)")
    body()
}

func run(_ name: String, _ body: () -> Void) {
    VFTestLog.current = name
    body()
}

    suite("CallDetectorTests") {
        let t = CallDetectorTests()
        run("CallDetectorTests.testNothingHappeningIsNotACall") { t.testNothingHappeningIsNotACall() }
        run("CallDetectorTests.testOurOwnWarmEngineIsNotMistakenForACall") { t.testOurOwnWarmEngineIsNotMistakenForACall() }
        run("CallDetectorTests.testTeamsOpenAllDayWithOurWarmMicIsNotACall") { t.testTeamsOpenAllDayWithOurWarmMicIsNotACall() }
        run("CallDetectorTests.testConferencingAppAloneIsNotACall") { t.testConferencingAppAloneIsNotACall() }
        run("CallDetectorTests.testCallStartsWhenAConferencingAppTakesTheMic") { t.testCallStartsWhenAConferencingAppTakesTheMic() }
        run("CallDetectorTests.testStartIsDebouncedSoABriefBlipDoesNotNag") { t.testStartIsDebouncedSoABriefBlipDoesNotNag() }
        run("CallDetectorTests.testCallEndsWhenTheMicIsReleased") { t.testCallEndsWhenTheMicIsReleased() }
        run("CallDetectorTests.testEndIsDebouncedAcrossAShortDropout") { t.testEndIsDebouncedAcrossAShortDropout() }
        run("CallDetectorTests.testCallDoesNotStartTwice") { t.testCallDoesNotStartTwice() }
        run("CallDetectorTests.testAnotherAppUsingTheMicWithoutAConferencingAppCountsAsACall") { t.testAnotherAppUsingTheMicWithoutAConferencingAppCountsAsACall() }
    }
    suite("DockPlacementTests") {
        let t = DockPlacementTests()
        run("DockPlacementTests.testUnknownScreenFallsBackToTheDefaultSpot") { t.testUnknownScreenFallsBackToTheDefaultSpot() }
        run("DockPlacementTests.testPositionIsRememberedPerScreen") { t.testPositionIsRememberedPerScreen() }
        run("DockPlacementTests.testRememberingAgainOverwritesThatScreenOnly") { t.testRememberingAgainOverwritesThatScreenOnly() }
    }
    suite("CallSourceTests") {
        let t = CallSourceTests()
        run("CallSourceTests.testHelperProcessNamesBecomeTheAppTheyBelongTo") { t.testHelperProcessNamesBecomeTheAppTheyBelongTo() }
        run("CallSourceTests.testUnknownAppsKeepTheirNameRatherThanBecomingGeneric") { t.testUnknownAppsKeepTheirNameRatherThanBecomingGeneric() }
        run("CallSourceTests.testTrailingHelperSuffixesAreStripped") { t.testTrailingHelperSuffixesAreStripped() }
        run("CallSourceTests.testTheOfferLineNeverReadsLikeAGlitch") { t.testTheOfferLineNeverReadsLikeAGlitch() }
        run("CallSourceTests.testAProcessIdIsNeverShownAsACall") { t.testAProcessIdIsNeverShownAsACall() }
        run("CallSourceTests.testAppNamesAlreadyEndingInCallAreNotDoubled") { t.testAppNamesAlreadyEndingInCallAreNotDoubled() }
    }
    suite("CaptureStateTests") {
        let t = CaptureStateTests()
        run("CaptureStateTests.testIdleTapFromCurrentEngineFillsPreroll") { t.testIdleTapFromCurrentEngineFillsPreroll() }
        run("CaptureStateTests.testRecordingTapFromCurrentEngineIsCaptured") { t.testRecordingTapFromCurrentEngineIsCaptured() }
        run("CaptureStateTests.testTapFromASupersededEngineIsDiscarded") { t.testTapFromASupersededEngineIsDiscarded() }
        run("CaptureStateTests.testTapStaysValidAcrossRecordStopIdleRecordCycles") { t.testTapStaysValidAcrossRecordStopIdleRecordCycles() }
        run("CaptureStateTests.testBeginRecordingTwiceIsRejected") { t.testBeginRecordingTwiceIsRejected() }
        run("CaptureStateTests.testRecordingStopsWhenTheEngineIsInvalidated") { t.testRecordingStopsWhenTheEngineIsInvalidated() }
        run("CaptureStateTests.testAllZeroAudioCondemnsADeviceONLYWhenItLastsLongEnough") { t.testAllZeroAudioCondemnsADeviceONLYWhenItLastsLongEnough() }
        run("CaptureStateTests.testShortNonZeroCaptureIsInconclusiveNotWorking") { t.testShortNonZeroCaptureIsInconclusiveNotWorking() }
        run("CaptureStateTests.testEmptyCaptureIsInconclusiveNotSilent") { t.testEmptyCaptureIsInconclusiveNotSilent() }
        run("CaptureStateTests.testLongNonZeroCaptureIsWorking") { t.testLongNonZeroCaptureIsWorking() }
        run("CaptureStateTests.testRingKeepsOnlyTheMostRecentAudioAndNeverGrows") { t.testRingKeepsOnlyTheMostRecentAudioAndNeverGrows() }
        run("CaptureStateTests.testDrainEmptiesTheRing") { t.testDrainEmptiesTheRing() }
        run("CaptureStateTests.testRingHandlesAppendLargerThanCapacity") { t.testRingHandlesAppendLargerThanCapacity() }
    }
    suite("DesignSystemTests") {
        let t = DesignSystemTests()
        run("DesignSystemTests.testSpacingIsOnThe4pxGrid") { t.testSpacingIsOnThe4pxGrid() }
        run("DesignSystemTests.testRadiusScale") { t.testRadiusScale() }
        run("DesignSystemTests.testReadTimeRoundsUpAndNeverShowsZero") { t.testReadTimeRoundsUpAndNeverShowsZero() }
        run("DesignSystemTests.testSentenceCaseLowersInteriorWordsButKeepsAcronymsAndNames") { t.testSentenceCaseLowersInteriorWordsButKeepsAcronymsAndNames() }
        run("DesignSystemTests.testShadowsAreWarmNotBlack") { t.testShadowsAreWarmNotBlack() }
    }
    suite("DockStateTests") {
        let t = DockStateTests()
        run("DockStateTests.testBeginEntersListening") { t.testBeginEntersListening() }
        run("DockStateTests.testFinishThenCompleteReturnsToIdle") { t.testFinishThenCompleteReturnsToIdle() }
        run("DockStateTests.testFailEntersErrorWithText") { t.testFailEntersErrorWithText() }
        run("DockStateTests.testToggleModeFlips") { t.testToggleModeFlips() }
        run("DockStateTests.testSetLevelClampsAndStoresWhileListening") { t.testSetLevelClampsAndStoresWhileListening() }
    }
    suite("MicHealthTests") {
        let t = MicHealthTests()
        run("MicHealthTests.testDeviceIsGivenTimeToWakeUpBeforeBeingJudged") { t.testDeviceIsGivenTimeToWakeUpBeforeBeingJudged() }
        run("MicHealthTests.testDeviceThatNeverDeliversIsStalledOnceGraceExpires") { t.testDeviceThatNeverDeliversIsStalledOnceGraceExpires() }
        run("MicHealthTests.testSignalMakesItLive") { t.testSignalMakesItLive() }
        run("MicHealthTests.testZeroFilledBuffersDoNotCountAsSignal") { t.testZeroFilledBuffersDoNotCountAsSignal() }
        run("MicHealthTests.testMicThatDiesMidStreamIsCaught") { t.testMicThatDiesMidStreamIsCaught() }
        run("MicHealthTests.testAPauseInSpeechIsNotAStall") { t.testAPauseInSpeechIsNotAStall() }
    }
    suite("MicLifecycleTests") {
        let t = MicLifecycleTests()
        run("MicLifecycleTests.testSecondStartIsRefusedWhileTheFirstIsStillComingUp") { t.testSecondStartIsRefusedWhileTheFirstIsStillComingUp() }
        run("MicLifecycleTests.testStartIsRefusedWhileStopIsStillRunning") { t.testStartIsRefusedWhileStopIsStillRunning() }
        run("MicLifecycleTests.testStopIsRefusedWhenNothingIsRecording") { t.testStopIsRefusedWhenNothingIsRecording() }
        run("MicLifecycleTests.testAFailedStartReturnsToIdleRatherThanWedgingTheMachine") { t.testAFailedStartReturnsToIdleRatherThanWedgingTheMachine() }
        run("MicLifecycleTests.testACallbackFromAReplacedEngineIsRejected") { t.testACallbackFromAReplacedEngineIsRejected() }
        run("MicLifecycleTests.testTearingDownSilencesTheTapBeforeStateIsReplaced") { t.testTearingDownSilencesTheTapBeforeStateIsReplaced() }
        run("MicLifecycleTests.testStopSilencesTapsSoNothingAppendsAfterTheMeetingEnds") { t.testStopSilencesTapsSoNothingAppendsAfterTheMeetingEnds() }
        run("MicLifecycleTests.testTwoBringUpsCannotOverlap") { t.testTwoBringUpsCannotOverlap() }
        run("MicLifecycleTests.testAWedgedBringUpIsAbandonedSoLaterAttemptsCanRun") { t.testAWedgedBringUpIsAbandonedSoLaterAttemptsCanRun() }
        run("MicLifecycleTests.testAnAbandonedAttemptCannotPublishOverItsReplacement") { t.testAnAbandonedAttemptCannotPublishOverItsReplacement() }
        run("MicLifecycleTests.testAnAttemptCannotPublishAfterTheMeetingHasStopped") { t.testAnAttemptCannotPublishAfterTheMeetingHasStopped() }
        run("MicLifecycleTests.testRecoveryIsBoundedAndThenReportsExhausted") { t.testRecoveryIsBoundedAndThenReportsExhausted() }
        run("MicLifecycleTests.testTheRecoveryBudgetResetsForEachMeeting") { t.testTheRecoveryBudgetResetsForEachMeeting() }
        run("MicLifecycleTests.testASecondRecoveryIsRefusedImmediately") { t.testASecondRecoveryIsRefusedImmediately() }
        run("MicLifecycleTests.testARecoveryWedgedBeforeTheMicEvenStartsCanBeAbandoned") { t.testARecoveryWedgedBeforeTheMicEvenStartsCanBeAbandoned() }
        run("MicLifecycleTests.testRecoveryIsRefusedWhenNoMeetingIsRunning") { t.testRecoveryIsRefusedWhenNoMeetingIsRunning() }
        run("MicLifecycleTests.testOrdinaryCallbackJitterIsNotPadded") { t.testOrdinaryCallbackJitterIsNotPadded() }
        run("MicLifecycleTests.testARealOutageIsPaddedToTheSystemClock") { t.testARealOutageIsPaddedToTheSystemClock() }
        run("MicLifecycleTests.testAMicAheadOfTheSystemTrackIsNeverPadded") { t.testAMicAheadOfTheSystemTrackIsNeverPadded() }
        run("MicLifecycleTests.testCoverageExcludesPaddingSoADeadMicCannotReport100") { t.testCoverageExcludesPaddingSoADeadMicCannotReport100() }
        run("MicLifecycleTests.testCoverageReportsDeliveredAudio") { t.testCoverageReportsDeliveredAudio() }
        run("MicLifecycleTests.testCoverageCannotExceed100") { t.testCoverageCannotExceed100() }
    }
    suite("SmokeTests") {
        let t = SmokeTests()
        run("SmokeTests.testExpandedDefaultsFalse") { t.testExpandedDefaultsFalse() }
        run("SmokeTests.testCompleteThenReturnToIdle") { t.testCompleteThenReturnToIdle() }
        run("SmokeTests.testFailIsRecoverable") { t.testFailIsRecoverable() }
        run("SmokeTests.testBeginClearsPriorError") { t.testBeginClearsPriorError() }
        run("SmokeTests.testLevelIgnoredOutsideListening") { t.testLevelIgnoredOutsideListening() }
    }
    suite("SpeakerTextTests") {
        let t = SpeakerTextTests()
        run("SpeakerTextTests.testExtractsSpeakerNamesInFirstAppearanceOrder") { t.testExtractsSpeakerNamesInFirstAppearanceOrder() }
        run("SpeakerTextTests.testReturnsEmptyWhenThereAreNoLabels") { t.testReturnsEmptyWhenThereAreNoLabels() }
        run("SpeakerTextTests.testIgnoresBoldThatIsNotASpeakerLabel") { t.testIgnoresBoldThatIsNotASpeakerLabel() }
    }

// --- drift check: every `func test…` on disk must be registered above ---
let fm = FileManager.default
var declared = 0
if let files = try? fm.contentsOfDirectory(atPath: "Sources/VFTests") {
    for f in files where f.hasSuffix(".swift") && f != "main.swift" && f != "XCTShim.swift" {
        if let src = try? String(contentsOfFile: "Sources/VFTests/" + f, encoding: .utf8) {
            declared += src.components(separatedBy: "\n").filter { $0.hasPrefix("    func test") }.count
        }
    }
}
let registered = 78
print("")
if declared > 0 && declared != registered {
    print("  ✘ DRIFT: \(declared) test functions on disk, \(registered) registered.")
    print("    Re-run: python3 ../scripts/gen_test_runner.py")
    exit(1)
}
if VFTestLog.failures.isEmpty {
    print("  \(registered) tests, \(VFTestLog.assertions) assertions — ALL PASS")
    exit(0)
} else {
    print(VFTestLog.failures.joined(separator: "\n"))
    print("")
    print("  \(VFTestLog.failures.count) failure(s) across \(registered) tests")
    exit(1)
}
