#!/usr/bin/env python3
"""Generate Sources/VFTests/main.swift.

XCTest finds test methods by reflection. Without XCTest they must be listed, so
this writes the list. It also emits a drift check: if a `func test…` exists on
disk but was never registered, the suite FAILS rather than quietly not running
it — the one way a hand-rolled runner could become a lie.

Run from client/:  python3 ../scripts/gen_test_runner.py
"""
import re, glob, os

DIR = "Sources/VFTests"
SKIP = {"XCTShim.swift", "main.swift"}
lines, total = [], 0

for path in sorted(glob.glob(f"{DIR}/*.swift")):
    if os.path.basename(path) in SKIP:
        continue
    src = open(path, encoding="utf-8").read()
    # Slice each class body at the NEXT class, or the generator double-counts
    # every method in a file that declares two test classes.
    classes = [(m.group(1), m.end()) for m in re.finditer(r"final class (\w+): XCTestCase \{", src)]
    for i, (name, start) in enumerate(classes):
        end = classes[i + 1][1] if i + 1 < len(classes) else len(src)
        body = src[start:end]
        methods = re.findall(r"\n    func (test\w+)\(\)", body)
        if not methods:
            continue
        lines.append(f'    suite("{name}") {{')
        lines.append(f'        let t = {name}()')
        for m in methods:
            lines.append(f'        run("{name}.{m}") {{ t.{m}() }}')
            total += 1
        lines.append("    }")

header = '''import Foundation

// GENERATED by scripts/gen_test_runner.py — re-run it after adding a test.
//
// XCTest ships only inside Xcode. When Xcode left this machine all 78 tests
// became unrunnable and audio concurrency code was changed for an evening with
// no safety net. The suite never needed the framework: it is pure logic using
// seven assertions, no setUp, no expectations, no async. So it runs as a plain
// executable instead — `swift run vf-tests` — with or without Xcode present.

func suite(_ name: String, _ body: () -> Void) {
    print("  \\(name)")
    body()
}

func run(_ name: String, _ body: () -> Void) {
    VFTestLog.current = name
    body()
}

'''

footer = f'''

// --- drift check: every `func test…` on disk must be registered above ---
let fm = FileManager.default
var declared = 0
if let files = try? fm.contentsOfDirectory(atPath: "{DIR}") {{
    for f in files where f.hasSuffix(".swift") && f != "main.swift" && f != "XCTShim.swift" {{
        if let src = try? String(contentsOfFile: "{DIR}/" + f, encoding: .utf8) {{
            declared += src.components(separatedBy: "\\n").filter {{ $0.hasPrefix("    func test") }}.count
        }}
    }}
}}
let registered = {total}
print("")
if declared > 0 && declared != registered {{
    print("  ✘ DRIFT: \\(declared) test functions on disk, \\(registered) registered.")
    print("    Re-run: python3 ../scripts/gen_test_runner.py")
    exit(1)
}}
if VFTestLog.failures.isEmpty {{
    print("  \\(registered) tests, \\(VFTestLog.assertions) assertions — ALL PASS")
    exit(0)
}} else {{
    print(VFTestLog.failures.joined(separator: "\\n"))
    print("")
    print("  \\(VFTestLog.failures.count) failure(s) across \\(registered) tests")
    exit(1)
}}
'''

open(f"{DIR}/main.swift", "w", encoding="utf-8").write(header + "\n".join(lines) + footer)
print(f"  registered {total} test functions")
